# Generated by Django 4.0.5 on 2022-06-04 23:58

from django.db import migrations, models
import username.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', username.models.UsernameModel(max_length=15, unique=True, verbose_name='Username')),
            ],
        ),
    ]
